myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [
    path(r'index/', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:top_no>/', views.detail, name='detail'),
    path(r'courses/',views.courses, name='courses'),
    path(r'<int:course_no>/add_interest/', views.add_interest, name='add_interest'),
    path(r'courses/<int:course_no>/', views.coursedetail, name='coursedetail'),
    path(r'placeorder', views.placeorder, name='placeorder'),
    path(r'login/', views.user_login, name='user_login'),
    path(r'logout/', views.user_logout, name='user_logout'),
    path(r'myaccount/', views.myaccount, name='myaccount')
]

mywebappS22/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),

]

myapp/models.py
from django.db import models
import datetime
import decimal
from django.contrib.auth.models import User
from django.db.models import Sum
from decimal import Decimal
from django.utils import timezone


class Topic(models.Model):
    name = models.CharField(max_length=200, null=True)
    category = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

    def get_category(self):
        return self.category

class Course(models.Model):
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    interested = models.PositiveIntegerField(default=0)
    stages = models.PositiveIntegerField(default=3)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)

    def __str__(self):
        return self.name

    def discount(self):
        discount_price = self.price - (self.price * Decimal('0.1'))
        return discount_price

class Student(User):
    CITY_CHOICES = [('WS', 'Windsor'),
                    ('CG', 'Calgary'),
                    ('MR', 'Montreal'),
                    ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
    interested_in = models.ManyToManyField(Topic)

    def __str__(self):
        return self.username + " " + self.last_name

    def bought_courses(self):
        return list(Order.objects.filter(student_id=self.id).values_list("course__name", flat=True))

    def interested_in_topics(self):
        return list(self.interested_in.values_list("name", flat=True))

class Order(models.Model):
    Status_Confirmation = [(0, 'Cancelled'),
                           (1, 'Order Confirmed')]
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    levels = models.PositiveIntegerField()
    order_status = models.IntegerField(choices=Status_Confirmation, default=1)
    order_date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.student.username

    def total_cost(self):
        return self.sum1+ self.course.price

class Interest(models.Model):
    interested = models.CharField(max_length=200)
    levels = models.IntegerField(default=1)
    comments = models.CharField(max_length=200, null=True)


class Tag(models.Model):
    name = models.CharField(max_length=20, default="", null=True)
    orders = models.ManyToManyField(Order)
    student = models.ForeignKey(Student, on_delete=models.DO_NOTHING, null=True)
    topic = models.OneToOneField(Topic, on_delete=models.CASCADE, null=True)

myapp/forms.py
from django import forms
from myapp.models import Order, Course, Topic, Student
import datetime
from django.forms import ModelForm, RadioSelect, SelectDateWidget
from django.core.validators import MinValueValidator

from .models import *

class StudentForm(forms.ModelForm):
    interested_in = forms.ModelMultipleChoiceField(queryset=Topic.objects.all(), widget=forms.CheckboxSelectMultiple())


class InterestForm(forms.Form):
    choice = [('1', 'Yes'), ('0', 'No')]
    interested = forms.CharField(label='Interested', widget=forms.RadioSelect(choices=choice))
    levels = forms.IntegerField(min_value=1, max_value=10)
    comments = forms.CharField(label='Additional Comments', widget=forms.Textarea(), required=False)

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ('student', 'course', 'levels', 'order_date')
        widgets = {
            'student': RadioSelect(),
            'order_date': SelectDateWidget()
        }
class LoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(widget=forms.PasswordInput())

myapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import InterestForm, OrderForm, LoginForm
from .models import Topic, Course, Student, Order, Interest
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.db.models import F
from django.contrib.auth import authenticate, login, logout, get_user
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.contrib.auth.signals import user_logged_out

def do_stuff(sender, user, request, **kwargs):
    request.delete_cookie('last_login')


user_logged_out.connect(do_stuff)

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                request.session['last_login'] = str(datetime.now())
                response = HttpResponseRedirect(reverse('myapp:index'))
                response.set_cookie('last_login', datetime.now() , max_age=3600)
                login(request, user)
                return response
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        context = {'form': LoginForm() }
        return render(request, 'myapp/login.html', context)

@login_required
def user_logout(request):
    #   logout(request)  # COMMENTING FOR PART 2C
    del request.session['last_login']
    response = HttpResponseRedirect(reverse('myapp:index'))
    response.delete_cookie('last_login')
    return response

@login_required
def myaccount(request):
    user = get_user(request)
    if hasattr(user, 'student'):
        student = user.student
        context = {
            'interested_in_topics': student.interested_in_topics,
            'bought_courses': student.bought_courses,
            'first_name': student.first_name,
            'last_name': student.last_name
        }
        return render(request, 'myapp/myaccount.html', context)
    else:
        msg = "You are not a registered student!"
        return render(request, 'myapp/not_student_account.html', {'msg': msg})

def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index.html', {'top_list': top_list})


def about(request):
    print("Welcome guys")
    return render(request, 'myapp/about.html')


def detail(request, top_no):
    response = HttpResponse()
    topics = Topic.objects.filter(id=top_no).values()
    if not topics:
        response.write(get_object_or_404(topics))
        return response

    # para = '<p> Category is:  ' + str(topics[0].get('category')) + '</p>'
    # response.write(para)
    courses = Course.objects.filter(topic=top_no)

    # response.write('<ul>')
    # for c in courses:
    # para = '<li>' + str(c) + '</li>'
    # response.write(para)
    # response.write('</ul>')
    return render(request, 'myapp/detail.html',
                  {'topic_name': topics[0].get('category'), 'name': topics[0].get('name'), 'courses': courses})
def placeorder(request):
    msg = ''
    courlist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.levels <= order.course.stages:
                order.save()
                course = order.course
                if course.price > 150:
                    course.price = course.discount()
                    course.save()
                msg = 'Your course has been ordered successfully.'
            else:
                msg = 'You exceeded the number of levels for this course.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
        return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'courlist': courlist})

def courses(request):
    course_list = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'course_list': course_list})

def coursedetail(request, course_no):
    course = get_object_or_404(Course, id=course_no)
    context = {'course': course}
    return render(request, 'myapp/coursedetail.html', context)

def add_interest(request, course_no):
    if request.method == 'POST':
        form = InterestForm(request.POST, request.FILES)
        if form.is_valid():
            interest = Interest()
            interest.interested = form.cleaned_data['interested']
            interest.levels = form.cleaned_data['levels']
            interest.comments = form.cleaned_data['comments']
            interest.save()
            course = get_object_or_404(Course, id=course_no)
            course.interested = F("interested") + 1
            course.save(update_fields=["interested"])

            return render(request, 'myapp/interest_success.html', {'msg': "Your Interest has been saved successfully."})
        else:
            context = {'form': InterestForm()}
            return render(request, 'myapp/interest.html', context)
    else:

        context = {'form': InterestForm(), 'course_id': get_object_or_404(Course, id=course_no).id}
        return render(request,'myapp/interest.html', context)

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}
    About
{% endblock %}
{% block body_block %}
    <h1>This is an E-learning Website! Search our Topics to find all available Courses.</h1>
{#    <p><a href="{% url 'myapp:index' %}">Go Back</a></p>#}
    <p>
        {% if request.session.last_login %}
            Last Logged In at : {{ request.session.last_login }}
            <p><a href="{% url 'myapp:user_logout' %}">Logout</a></p>
        {% else %}
            Your last login was more than one hour ago
            <p><a href="{% url 'myapp:user_login' %}">Login</a></p>
        {% endif %}
    </p>
    <p><a href="{% url 'myapp:about' %}">About page</a></p>

    <p><a href="{% url 'myapp:courses' %}">All Courses</a></p>
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>About Page</title>
    </head>
    <body>
        <p>
            <h1> This is an e-learning website
            </h1>
        </p>
        <p>
            <a href="{% url "myapp:index" %}">Index page</a>
        </p>
    </body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
   <head>
      <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
      <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
   </head>
   <body>
      <div>
         <h1>{% block myhdg %}Hello Group7 {% endblock %}</h1>
         {% block body_block %}* {% endblock %}
      </div>
      <hr />
      <div>
         <ul>
          <li class="hbar1"><a href="/myapp/about/">Find out about our ELearning site</a></li>
          <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a></li>
             <!--<li class="hbar1"><a href="{% url 'myapp:courses' %}">Course List</a></li> -->




         </ul>
      </div>
   </body>
</html>

myapp/templates/myapp/coursedetail.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <a href="{% url 'myapp:courses' %}">Back to all courses</a>
    <b><a href="{% url 'myapp:add_interest' course.id %}">Add Interest</a> </b>
    <p><b>Course Details:</b></p>
    <ul>
        <li>
            <b>Name: </b>{{ course.name}}
        </li>
        <li>
            <b>Price: </b>{{ course.price }}
        </li>
        <li>
            <b>No of students Interested: </b>{{ course.interested }}
        </li>
        <li>
            <b>For Everyone: </b>{{ course.for_everyone }}
        </li>

    </ul>
{% endblock %}

myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <a href="{% url 'myapp:placeorder' %}">New Order</a>
    <p><b>Courses:</b></p>


    {% if course_list %}
        <ol>
            {% for course in course_list %}
                <li>
                    <a href="{% url 'myapp:coursedetail' course.id %}">{{ course.name}}</a>
                </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available courses!</strong>
    {% endif %}
{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}
    Details
{% endblock %}
{% block body_block %}
    <p><b>Topic:</b> {{ name }} </p>
    <p><b>Category:</b> {{ topic_name }}</p>

    {% if courses %}

    {% for course in courses %}
        <li> {{course}} </li>
    {% endfor %}

    {% else %}
        <p> No Course found for this topic </p>
    {% endif %}
{#    <p><a href="{% url 'myapp:index' %}">Go Back</a></p>#}
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Topic - {{ topic_name }}</title>
</head>
<body>
    <h1>Name - {{ name }}</h1>
    <h2>Category - {{ topic_name }}</h2>
    <h3>Courses in the above topics</h3>

    {% for course  in courses %}
        <li> {{course}} </li>
    {% endfor %}

    <p>
        <a href="{% url "myapp:index" %}">Home page</a>
    </p>

</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}{% block body_block %}{% endblock %}
<body>
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for top  in top_list %}
                <li> <a href="{{ top.id }}">{{ top.name}}</a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
    <p><a href="/myapp/about">About Page</a></p>
</body>

myapp/templates/myapp/interest.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <div class="form_container">
        <form action="{% url "myapp:add_interest" course_id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-3">
                <label for="formFile" class="form-label" style="display: block;">
                    <h4 style="margin-bottom: 2rem;">Interest Form</h4>
                </label>

                <label for="interested" class="form-label" style="display: block;">
                    <h4> Interested </h4>
                    {{  form.interested }}
                </label>

                <label for="levels" class="form-label" style="display: block;">
                    <h4> Levels </h4>
                    {{  form.levels }}
                </label>

                <label for="comments" class="form-label" style="display: block;">
                    <h4> Comments </h4>
                    {{  form.comments }}
                </label>

                <input type="submit" value="Submit" class="btn btn-lg btn-secondary convert_button" />

            </div>
        </form>
    </div>
    <p><a href="{% url 'myapp:about' %}">About page</a></p>

    <p><a href="{% url 'myapp:courses' %}">All Courses</a></p>
{% endblock %}

myapp/templates/myapp/interest_success.html
{% block body_block %}
<p><b>Your Interest has been saved successfully</b></p>
{% endblock %}

myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <a href="{% url 'myapp:courses' %}">Back to all courses</a>
    <p><b>Course Details:</b></p>
    <ul>
        <li>
            <b>Name: </b>{{ first_name }} {{ last_name }}
        </li>
        <li>
            <b>Courses: </b>{{ bought_courses }}
        </li>
        <li>
            <b>Topic: </b>{{ interested_in_topics }}
        </li>

    </ul>

     <p><a href="{% url 'myapp:about' %}">About page</a></p>

     <p><a href="{% url 'myapp:courses' %}">All Courses</a></p>
{% endblock %}

myapp/templates/myapp/not_student_account.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h2>{{ msg }}</h2>

     <p><a href="{%url 'myapp:about' %}">About page</a></p>

     <p><a href="{% url 'myapp:courses' %}">All Courses</a></p>
{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <h2>{{ msg }}</h2>
     <p><a href="{% url 'myapp:about' %}">About page</a></p>

     <p><a href="{% url 'myapp:courses' %}">All Courses</a></p>
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block body_block %}

    <div class="form_container">
        <form action="{% url "myapp:placeorder" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>{{ msg }}</h2>
            <div class="mb-3">
                <label for="formFile" class="form-label" style="display: block;">
                    <h4 style="margin-bottom: 2rem;">Order Form</h4>
                </label>

                <label for="course" class="form-label" style="display: block;">
                    <h4> Course </h4>
                    {{  form.course }}
                </label>

                <label for="student" class="form-label" style="display: block;">
                    <h4> Student </h4>
                    {{  form.student }}
                </label>


                <label for="levels" class="form-label" style="display: block;">
                    <h4> Levels </h4>
                    {{  form.levels }}
                </label>

                <label for="order_date" class="form-label" style="display: block;">
                    <h4> Order Date </h4>
                    {{  form.order_date }}
                </label>

                <input type="submit" value="Submit" class="btn btn-lg btn-secondary convert_button" />

            </div>
        </form>
    </div>



     <p><a href="{% url 'myapp:about' %}">About page</a></p>

     <p><a href="{% url 'myapp:courses' %}">All Courses</a></p>
{% endblock %}